apiVersion: v1
kind: Namespace
metadata:
  labels:
    cis_scanner_zone: zone_1
  name: cloudadc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: cloudadc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: cloudadc/backend:0.0.7
        name: backend
        ports:
        - containerPort: 8080
        env:
        - name: APP_DATACENTER_NAME
          value: "Cloud ADC"
        - name: APP_VERSION_NUMBER
          value: "1.0"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
    cis.f5.com/as3-tenant: "cloudadc"
    cis.f5.com/as3-app: "cloudadc"
    cis.f5.com/as3-pool: "cloudadc_app_svc_pool"
  name: app-svc
  namespace: cloudadc
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  type: NodePort

