apiVersion: v1
kind: Namespace
metadata:
  name: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zookeeper
  name: zookeeper
  namespace: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy: {}
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: cloudadc/zookeeper:1.0
        name: zookeeper
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper-svc
  namespace: zookeeper
spec:
  ports:
  - port: 2181
    name: zookeeper
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: loan-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: loan-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:5.0.5
        name: mongodb
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb-svc
  namespace: loan-db
spec:
  ports:
  - port: 27017
    name: mongodb
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: loan-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: provider
  name: provider
  namespace: loan-provider
spec:
  replicas: 2
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - image: cloudadc/loan-provider:1.0
        name: provider
        ports:
        - containerPort: 20880
        env:
        - name: DUBBO_REGISTRY_PROXY_ADDRESS
          value: "zookeeper-svc.zookeeper.svc.cluster.local"
        - name: MONGODB_SERVER_ADDRESS
          value: "mongodb-svc.loan-db.svc.cluster.local"
---
apiVersion: v1
kind: Namespace
metadata:
  name: loan-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
  namespace: loan-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - image: cloudadc/loan-consumer:1.0
        name: consumer
        ports:
        - containerPort: 8080
        env:
        - name: DUBBO_REGISTRY_PROXY_ADDRESS
          value: "zookeeper-svc.zookeeper.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer
  name: consumer-svc
  namespace: loan-consumer
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: consumer
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer
  name: consumer-svc-nodeport
  namespace: loan-consumer
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
    nodePort: 30036
  selector:
    app: consumer
  type: NodePort
